//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapBox.Snap.LD.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoapBox.Snap.LD.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Instruction_Delete {
            get {
                return ResourceManager.GetString("Instruction_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this one instruction.
        /// </summary>
        public static string Instruction_Delete_ToolTip {
            get {
                return ResourceManager.GetString("Instruction_Delete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append Branch.
        /// </summary>
        public static string Instruction_Parallel_AppendBranch {
            get {
                return ResourceManager.GetString("Instruction_Parallel_AppendBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new branch to the bottom.
        /// </summary>
        public static string Instruction_Parallel_AppendBranch_ToolTip {
            get {
                return ResourceManager.GetString("Instruction_Parallel_AppendBranch_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Empty Branches.
        /// </summary>
        public static string Instruction_Parallel_RemoveEmptyBranches {
            get {
                return ResourceManager.GetString("Instruction_Parallel_RemoveEmptyBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes branches that have no instructions.
        /// </summary>
        public static string Instruction_Parallel_RemoveEmptyBranches_ToolTip {
            get {
                return ResourceManager.GetString("Instruction_Parallel_RemoveEmptyBranches_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladder Logic.
        /// </summary>
        public static string InstructionGroup_Header {
            get {
                return ResourceManager.GetString("InstructionGroup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Down.
        /// </summary>
        public static string LD_Snap_CntDN_InstructionName {
            get {
                return ResourceManager.GetString("LD_Snap_CntDN_InstructionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Up.
        /// </summary>
        public static string LD_Snap_CntUP_InstructionName {
            get {
                return ResourceManager.GetString("LD_Snap_CntUP_InstructionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Coil.
        /// </summary>
        public static string LD_Snap_Coil_DefaultCoilName {
            get {
                return ResourceManager.GetString("LD_Snap_Coil_DefaultCoilName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coil.
        /// </summary>
        public static string LD_Snap_Coil_InstructionName {
            get {
                return ResourceManager.GetString("LD_Snap_Coil_InstructionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count:.
        /// </summary>
        public static string LD_Snap_Ctr_CountLabel {
            get {
                return ResourceManager.GetString("LD_Snap_Ctr_CountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string LD_Snap_Ctr_CountName {
            get {
                return ResourceManager.GetString("LD_Snap_Ctr_CountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Counter.
        /// </summary>
        public static string LD_Snap_Ctr_DefaultName {
            get {
                return ResourceManager.GetString("LD_Snap_Ctr_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rung In.
        /// </summary>
        public static string LD_Snap_Ctr_OneshotStateName {
            get {
                return ResourceManager.GetString("LD_Snap_Ctr_OneshotStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset:.
        /// </summary>
        public static string LD_Snap_Ctr_ResetLabel {
            get {
                return ResourceManager.GetString("LD_Snap_Ctr_ResetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setpoint:.
        /// </summary>
        public static string LD_Snap_Ctr_SetpointLabel {
            get {
                return ResourceManager.GetString("LD_Snap_Ctr_SetpointLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falling Edge.
        /// </summary>
        public static string LD_Snap_FallingEdge_InstructionName {
            get {
                return ResourceManager.GetString("LD_Snap_FallingEdge_InstructionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rising Edge.
        /// </summary>
        public static string LD_Snap_RisingEdge_DefaultName {
            get {
                return ResourceManager.GetString("LD_Snap_RisingEdge_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rising Edge.
        /// </summary>
        public static string LD_Snap_RisingEdge_InstructionName {
            get {
                return ResourceManager.GetString("LD_Snap_RisingEdge_InstructionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Set-Reset.
        /// </summary>
        public static string LD_Snap_SetReset_DefaultName {
            get {
                return ResourceManager.GetString("LD_Snap_SetReset_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set/Reset.
        /// </summary>
        public static string LD_Snap_SetReset_InstructionName {
            get {
                return ResourceManager.GetString("LD_Snap_SetReset_InstructionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset:.
        /// </summary>
        public static string LD_Snap_SetReset_ResetLabel {
            get {
                return ResourceManager.GetString("LD_Snap_SetReset_ResetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Sensitive:.
        /// </summary>
        public static string LD_Snap_StringContains_CaseSensitiveLabel {
            get {
                return ResourceManager.GetString("LD_Snap_StringContains_CaseSensitiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Find Text.
        /// </summary>
        public static string LD_Snap_StringContains_DefaultName {
            get {
                return ResourceManager.GetString("LD_Snap_StringContains_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Text.
        /// </summary>
        public static string LD_Snap_StringContains_InstructionName {
            get {
                return ResourceManager.GetString("LD_Snap_StringContains_InstructionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Find:.
        /// </summary>
        public static string LD_Snap_StringContains_StringToFindLabel {
            get {
                return ResourceManager.GetString("LD_Snap_StringContains_StringToFindLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to Search:.
        /// </summary>
        public static string LD_Snap_StringContains_StringToSearchLabel {
            get {
                return ResourceManager.GetString("LD_Snap_StringContains_StringToSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Timer.
        /// </summary>
        public static string LD_Snap_Tmr_DefaultName {
            get {
                return ResourceManager.GetString("LD_Snap_Tmr_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed (ms):.
        /// </summary>
        public static string LD_Snap_Tmr_ElapsedLabel {
            get {
                return ResourceManager.GetString("LD_Snap_Tmr_ElapsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed.
        /// </summary>
        public static string LD_Snap_Tmr_ElapsedName {
            get {
                return ResourceManager.GetString("LD_Snap_Tmr_ElapsedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setpoint (ms):.
        /// </summary>
        public static string LD_Snap_Tmr_SetpointLabel {
            get {
                return ResourceManager.GetString("LD_Snap_Tmr_SetpointLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Off Timer.
        /// </summary>
        public static string LD_Snap_TmrOFF_InstructionName {
            get {
                return ResourceManager.GetString("LD_Snap_TmrOFF_InstructionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay On Timer.
        /// </summary>
        public static string LD_Snap_TmrON_InstructionName {
            get {
                return ResourceManager.GetString("LD_Snap_TmrON_InstructionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Down Counter.
        /// </summary>
        public static string ToolTipCntDN {
            get {
                return ResourceManager.GetString("ToolTipCntDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Up Counter.
        /// </summary>
        public static string ToolTipCntUP {
            get {
                return ResourceManager.GetString("ToolTipCntUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coil.
        /// </summary>
        public static string ToolTipCoil {
            get {
                return ResourceManager.GetString("ToolTipCoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normally Closed Contact.
        /// </summary>
        public static string ToolTipContactNC {
            get {
                return ResourceManager.GetString("ToolTipContactNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normally Open Contact.
        /// </summary>
        public static string ToolTipContactNO {
            get {
                return ResourceManager.GetString("ToolTipContactNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falling Edge Detection.
        /// </summary>
        public static string ToolTipFallingEdge {
            get {
                return ResourceManager.GetString("ToolTipFallingEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Branch(es).
        /// </summary>
        public static string ToolTipParallel {
            get {
                return ResourceManager.GetString("ToolTipParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rising Edge Detection.
        /// </summary>
        public static string ToolTipRisingEdge {
            get {
                return ResourceManager.GetString("ToolTipRisingEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set/Reset Coil.
        /// </summary>
        public static string ToolTipSetReset {
            get {
                return ResourceManager.GetString("ToolTipSetReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Text: Detects one piece of text inside of another.
        /// </summary>
        public static string ToolTipStringContains {
            get {
                return ResourceManager.GetString("ToolTipStringContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay-off Timer.
        /// </summary>
        public static string ToolTipTmrOFF {
            get {
                return ResourceManager.GetString("ToolTipTmrOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay-on Timer.
        /// </summary>
        public static string ToolTipTmrON {
            get {
                return ResourceManager.GetString("ToolTipTmrON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited coil description.
        /// </summary>
        public static string Undo_Action_EditCoilDescription {
            get {
                return ResourceManager.GetString("Undo_Action_EditCoilDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited coil name.
        /// </summary>
        public static string Undo_Action_EditCoilName {
            get {
                return ResourceManager.GetString("Undo_Action_EditCoilName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited contact signal.
        /// </summary>
        public static string Undo_Action_EditContactSignal {
            get {
                return ResourceManager.GetString("Undo_Action_EditContactSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited counter description.
        /// </summary>
        public static string Undo_Action_EditCtrDescription {
            get {
                return ResourceManager.GetString("Undo_Action_EditCtrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited counter name.
        /// </summary>
        public static string Undo_Action_EditCtrName {
            get {
                return ResourceManager.GetString("Undo_Action_EditCtrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited counter setpoint.
        /// </summary>
        public static string Undo_Action_EditCtrSetpointSignal {
            get {
                return ResourceManager.GetString("Undo_Action_EditCtrSetpointSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited edge detect description.
        /// </summary>
        public static string Undo_Action_EditEdgeDescription {
            get {
                return ResourceManager.GetString("Undo_Action_EditEdgeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited edge detect name.
        /// </summary>
        public static string Undo_Action_EditEdgeName {
            get {
                return ResourceManager.GetString("Undo_Action_EditEdgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited falling edge description.
        /// </summary>
        public static string Undo_Action_EditFallingEdgeDescription {
            get {
                return ResourceManager.GetString("Undo_Action_EditFallingEdgeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited falling edge name.
        /// </summary>
        public static string Undo_Action_EditFallingEdgeName {
            get {
                return ResourceManager.GetString("Undo_Action_EditFallingEdgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited counter reset signal.
        /// </summary>
        public static string Undo_Action_EditResetSignal {
            get {
                return ResourceManager.GetString("Undo_Action_EditResetSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited set/reset description.
        /// </summary>
        public static string Undo_Action_EditSetResetDescription {
            get {
                return ResourceManager.GetString("Undo_Action_EditSetResetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited set/reset name.
        /// </summary>
        public static string Undo_Action_EditSetResetName {
            get {
                return ResourceManager.GetString("Undo_Action_EditSetResetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited set/reset input signal.
        /// </summary>
        public static string Undo_Action_EditSetResetSignal {
            get {
                return ResourceManager.GetString("Undo_Action_EditSetResetSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited find text description.
        /// </summary>
        public static string Undo_Action_EditStringContainsDescription {
            get {
                return ResourceManager.GetString("Undo_Action_EditStringContainsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited find text name.
        /// </summary>
        public static string Undo_Action_EditStringContainsName {
            get {
                return ResourceManager.GetString("Undo_Action_EditStringContainsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited find text input signal.
        /// </summary>
        public static string Undo_Action_EditStringContainsSignal {
            get {
                return ResourceManager.GetString("Undo_Action_EditStringContainsSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited timer description.
        /// </summary>
        public static string Undo_Action_EditTmrDescription {
            get {
                return ResourceManager.GetString("Undo_Action_EditTmrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited timer name.
        /// </summary>
        public static string Undo_Action_EditTmrName {
            get {
                return ResourceManager.GetString("Undo_Action_EditTmrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited timer setpoint.
        /// </summary>
        public static string Undo_Action_EditTmrSetpointSignal {
            get {
                return ResourceManager.GetString("Undo_Action_EditTmrSetpointSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append branch.
        /// </summary>
        public static string Undo_Action_Instruction_Parallel_AppendBranch {
            get {
                return ResourceManager.GetString("Undo_Action_Instruction_Parallel_AppendBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing empty branches.
        /// </summary>
        public static string Undo_Action_Instruction_Parallel_RemoveEmptyBranches {
            get {
                return ResourceManager.GetString("Undo_Action_Instruction_Parallel_RemoveEmptyBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected instructions.
        /// </summary>
        public static string Undo_Action_Instruction_Series_DeleteSelected {
            get {
                return ResourceManager.GetString("Undo_Action_Instruction_Series_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert instructions.
        /// </summary>
        public static string Undo_Action_Instruction_Series_Insert {
            get {
                return ResourceManager.GetString("Undo_Action_Instruction_Series_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move instructions.
        /// </summary>
        public static string Undo_Action_Instruction_Series_Move {
            get {
                return ResourceManager.GetString("Undo_Action_Instruction_Series_Move", resourceCulture);
            }
        }
    }
}
