//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapBox.Snap.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoapBox.Snap.Application.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoapBox Snap.
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2009 by SoapBox Automation Inc.  All rights reserved..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released under the terms of the .
        /// </summary>
        public static string Copyright_License_Preamble {
            get {
                return ResourceManager.GetString("Copyright_License_Preamble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string GetConstantDialog_Buttons_Cancel {
            get {
                return ResourceManager.GetString("GetConstantDialog_Buttons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Ok   .
        /// </summary>
        public static string GetConstantDialog_Buttons_Ok {
            get {
                return ResourceManager.GetString("GetConstantDialog_Buttons_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value:.
        /// </summary>
        public static string GetConstantDialog_Header {
            get {
                return ResourceManager.GetString("GetConstantDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Value.
        /// </summary>
        public static string GetConstantDialog_Title {
            get {
                return ResourceManager.GetString("GetConstantDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instruction_Pad_Title {
            get {
                return ResourceManager.GetString("Instruction_Pad_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Options_ApplicationOptions_General {
            get {
                return ResourceManager.GetString("Options_ApplicationOptions_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open SoapBox Snap Start Page at Startup.
        /// </summary>
        public static string Options_ApplicationOptions_General_AutoOpenStartPage {
            get {
                return ResourceManager.GetString("Options_ApplicationOptions_General_AutoOpenStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Options_ApplicationOptions_Header {
            get {
                return ResourceManager.GetString("Options_ApplicationOptions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cancel Edit.
        /// </summary>
        public static string PageEditor_CommentButtons_Cancel {
            get {
                return ResourceManager.GetString("PageEditor_CommentButtons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Apply Edit.
        /// </summary>
        public static string PageEditor_CommentButtons_Commit {
            get {
                return ResourceManager.GetString("PageEditor_CommentButtons_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Edit Comment.
        /// </summary>
        public static string PageEditor_CommentButtons_Edit {
            get {
                return ResourceManager.GetString("PageEditor_CommentButtons_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Syntax Help.
        /// </summary>
        public static string PageEditor_CommentButtons_Markdown {
            get {
                return ResourceManager.GetString("PageEditor_CommentButtons_Markdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a web page with information about the Markdown syntax used here to write rich HTML comments.
        /// </summary>
        public static string PageEditor_CommentButtons_Markdown_ToolTip {
            get {
                return ResourceManager.GetString("PageEditor_CommentButtons_Markdown_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand/Collapse Page Comment.
        /// </summary>
        public static string PageEditor_CommentExpanderHeader {
            get {
                return ResourceManager.GetString("PageEditor_CommentExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert at Bottom.
        /// </summary>
        public static string PageEditor_GroupCommand_Append {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_Append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string PageEditor_GroupCommand_Delete {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this instruction group.
        /// </summary>
        public static string PageEditor_GroupCommand_Delete_ToolTip {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_Delete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert After Selected Group (Rung).
        /// </summary>
        public static string PageEditor_GroupCommand_InsertAfter {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_InsertAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Before Selected Group (Rung).
        /// </summary>
        public static string PageEditor_GroupCommand_InsertBefore {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_InsertBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Selected Group Down.
        /// </summary>
        public static string PageEditor_GroupCommand_MoveDown {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the selected group (e.g. rung) below the next group on the page.
        /// </summary>
        public static string PageEditor_GroupCommand_MoveDown_ToolTip {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_MoveDown_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Selected Group Up.
        /// </summary>
        public static string PageEditor_GroupCommand_MoveUp {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the selected group (e.g. rung) above the previous group on the page.
        /// </summary>
        public static string PageEditor_GroupCommand_MoveUp_ToolTip {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_MoveUp_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a single instruction group (e.g. rung) before using this command.
        /// </summary>
        public static string PageEditor_GroupCommand_NoneSelected {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_NoneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No group selected.
        /// </summary>
        public static string PageEditor_GroupCommand_NoneSelected_Title {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_NoneSelected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string PageEditor_GroupCommand_Redo {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo last action.
        /// </summary>
        public static string PageEditor_GroupCommand_Redo_ToolTip {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_Redo_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string PageEditor_GroupCommand_Undo {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo last action.
        /// </summary>
        public static string PageEditor_GroupCommand_Undo_ToolTip {
            get {
                return ResourceManager.GetString("PageEditor_GroupCommand_Undo_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected instruction groups.
        /// </summary>
        public static string PageEditor_UndoDescription_DeleteSelectedGroups {
            get {
                return ResourceManager.GetString("PageEditor_UndoDescription_DeleteSelectedGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited Page Comment.
        /// </summary>
        public static string PageEditor_UndoDescription_EditComment {
            get {
                return ResourceManager.GetString("PageEditor_UndoDescription_EditComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted instruction group.
        /// </summary>
        public static string PageEditor_UndoDescription_InsertGroup {
            get {
                return ResourceManager.GetString("PageEditor_UndoDescription_InsertGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move instruction group down.
        /// </summary>
        public static string PageEditor_UndoDescription_MoveGroupDown {
            get {
                return ResourceManager.GetString("PageEditor_UndoDescription_MoveGroupDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move selected instruction groups.
        /// </summary>
        public static string PageEditor_UndoDescription_MoveGroups {
            get {
                return ResourceManager.GetString("PageEditor_UndoDescription_MoveGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move instruction group up.
        /// </summary>
        public static string PageEditor_UndoDescription_MoveGroupUp {
            get {
                return ResourceManager.GetString("PageEditor_UndoDescription_MoveGroupUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string RuntimeApplication_Address {
            get {
                return ResourceManager.GetString("RuntimeApplication_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address or connection info here, like an IP address or COM Port.
        /// </summary>
        public static string RuntimeApplication_Address_Tooltip {
            get {
                return ResourceManager.GetString("RuntimeApplication_Address_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string RuntimeApplication_ApplyButton_Text {
            get {
                return ResourceManager.GetString("RuntimeApplication_ApplyButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string RuntimeApplication_CancelButton_Text {
            get {
                return ResourceManager.GetString("RuntimeApplication_CancelButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime Name:.
        /// </summary>
        public static string RuntimeApplication_Code {
            get {
                return ResourceManager.GetString("RuntimeApplication_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        public static string RuntimeApplication_Code_Default {
            get {
                return ResourceManager.GetString("RuntimeApplication_Code_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Runtime Name can only contain letters, numbers, and underscores only, and it must start with a letter..
        /// </summary>
        public static string RuntimeApplication_Code_Tooltip {
            get {
                return ResourceManager.GetString("RuntimeApplication_Code_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration:.
        /// </summary>
        public static string RuntimeApplication_Configuration {
            get {
                return ResourceManager.GetString("RuntimeApplication_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter custom configuration data here, specific to the type or Runtime.
        /// </summary>
        public static string RuntimeApplication_Configuration_Tooltip {
            get {
                return ResourceManager.GetString("RuntimeApplication_Configuration_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute on startup.
        /// </summary>
        public static string RuntimeApplication_ExecuteOnStartup {
            get {
                return ResourceManager.GetString("RuntimeApplication_ExecuteOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Runtime Application.
        /// </summary>
        public static string RuntimeApplication_NewTitle {
            get {
                return ResourceManager.GetString("RuntimeApplication_NewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string RuntimeApplication_OkButton_Text {
            get {
                return ResourceManager.GetString("RuntimeApplication_OkButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string RuntimeApplication_Type {
            get {
                return ResourceManager.GetString("RuntimeApplication_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RuntimeApplication_Type_Tooltip {
            get {
                return ResourceManager.GetString("RuntimeApplication_Type_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t make this edit while connected.  Do you want to disconnect?.
        /// </summary>
        public static string RuntimeService_Disconnect_Message {
            get {
                return ResourceManager.GetString("RuntimeService_Disconnect_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect?.
        /// </summary>
        public static string RuntimeService_Disconnect_Title {
            get {
                return ResourceManager.GetString("RuntimeService_Disconnect_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SignalChooserDialog_Buttons_Cancel {
            get {
                return ResourceManager.GetString("SignalChooserDialog_Buttons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Ok     .
        /// </summary>
        public static string SignalChooserDialog_Buttons_Ok {
            get {
                return ResourceManager.GetString("SignalChooserDialog_Buttons_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard coded value:.
        /// </summary>
        public static string SignalChooserDialog_LiteralHeader {
            get {
                return ResourceManager.GetString("SignalChooserDialog_LiteralHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An existing coil or signal:.
        /// </summary>
        public static string SignalChooserDialog_SignalHeader {
            get {
                return ResourceManager.GetString("SignalChooserDialog_SignalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Chooser.
        /// </summary>
        public static string SignalChooserDialog_Title {
            get {
                return ResourceManager.GetString("SignalChooserDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close current solution.
        /// </summary>
        public static string Solution_Command_Tooltip_Close {
            get {
                return ResourceManager.GetString("Solution_Command_Tooltip_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new solution (blank, or from a template).
        /// </summary>
        public static string Solution_Command_Tooltip_New {
            get {
                return ResourceManager.GetString("Solution_Command_Tooltip_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a solution from disk.
        /// </summary>
        public static string Solution_Command_Tooltip_Open {
            get {
                return ResourceManager.GetString("Solution_Command_Tooltip_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to this solution.
        /// </summary>
        public static string Solution_Command_Tooltip_Save {
            get {
                return ResourceManager.GetString("Solution_Command_Tooltip_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this solution to a new file.
        /// </summary>
        public static string Solution_Command_Tooltip_SaveAs {
            get {
                return ResourceManager.GetString("Solution_Command_Tooltip_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes to the existing solution.  Do you want to Save?.
        /// </summary>
        public static string Solution_Confirm_DoYouWantToSave {
            get {
                return ResourceManager.GetString("Solution_Confirm_DoYouWantToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        public static string Solution_Confirm_DoYouWantToSave_Title {
            get {
                return ResourceManager.GetString("Solution_Confirm_DoYouWantToSave_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap Solutions.
        /// </summary>
        public static string Solution_Extension_Description {
            get {
                return ResourceManager.GetString("Solution_Extension_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory was not found..
        /// </summary>
        public static string Solution_Open_DirectoryNotFoundException {
            get {
                return ResourceManager.GetString("Solution_Open_DirectoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not Found.
        /// </summary>
        public static string Solution_Open_DirectoryNotFoundException_Title {
            get {
                return ResourceManager.GetString("Solution_Open_DirectoryNotFoundException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be found..
        /// </summary>
        public static string Solution_Open_FileNotFoundException {
            get {
                return ResourceManager.GetString("Solution_Open_FileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not Found.
        /// </summary>
        public static string Solution_Open_FileNotFoundException_Title {
            get {
                return ResourceManager.GetString("Solution_Open_FileNotFoundException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file format of the solution file was not a valid SoapBox Snap solution..
        /// </summary>
        public static string Solution_Open_InvalidDataException {
            get {
                return ResourceManager.GetString("Solution_Open_InvalidDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        public static string Solution_Open_InvalidDataException_Title {
            get {
                return ResourceManager.GetString("Solution_Open_InvalidDataException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path is too long..
        /// </summary>
        public static string Solution_Open_PathTooLongException {
            get {
                return ResourceManager.GetString("Solution_Open_PathTooLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path too Long.
        /// </summary>
        public static string Solution_Open_PathTooLongException_Title {
            get {
                return ResourceManager.GetString("Solution_Open_PathTooLongException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient privileges to access this file..
        /// </summary>
        public static string Solution_Open_UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("Solution_Open_UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Access.
        /// </summary>
        public static string Solution_Open_UnauthorizedAccessException_Title {
            get {
                return ResourceManager.GetString("Solution_Open_UnauthorizedAccessException_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Solution....
        /// </summary>
        public static string Solution_OpenFileDialog_Title {
            get {
                return ResourceManager.GetString("Solution_OpenFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force.
        /// </summary>
        public static string Solution_Pad_AnalogInputItem_Force {
            get {
                return ResourceManager.GetString("Solution_Pad_AnalogInputItem_Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the input to a specific value, regardless of the actual hardware input.
        /// </summary>
        public static string Solution_Pad_AnalogInputItem_Force_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_AnalogInputItem_Force_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Force.
        /// </summary>
        public static string Solution_Pad_AnalogInputItem_RemoveForce {
            get {
                return ResourceManager.GetString("Solution_Pad_AnalogInputItem_RemoveForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes any active force on the output, so it will return control to the application logic.
        /// </summary>
        public static string Solution_Pad_AnalogInputItem_RemoveForce_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_AnalogInputItem_RemoveForce_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force.
        /// </summary>
        public static string Solution_Pad_AnalogOutputItem_Force {
            get {
                return ResourceManager.GetString("Solution_Pad_AnalogOutputItem_Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the output to a specific value, regardless of the logic driving it.
        /// </summary>
        public static string Solution_Pad_AnalogOutputItem_Force_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_AnalogOutputItem_Force_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Force.
        /// </summary>
        public static string Solution_Pad_AnalogOutputItem_RemoveForce {
            get {
                return ResourceManager.GetString("Solution_Pad_AnalogOutputItem_RemoveForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes any active force on the output, so it will return control to the application logic.
        /// </summary>
        public static string Solution_Pad_AnalogOutputItem_RemoveForce_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_AnalogOutputItem_RemoveForce_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your work?.
        /// </summary>
        public static string Solution_Pad_Closing_SaveMessage {
            get {
                return ResourceManager.GetString("Solution_Pad_Closing_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved work.
        /// </summary>
        public static string Solution_Pad_Closing_SaveTitle {
            get {
                return ResourceManager.GetString("Solution_Pad_Closing_SaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Configuration.
        /// </summary>
        public static string Solution_Pad_DeviceConfigurationItem_Header {
            get {
                return ResourceManager.GetString("Solution_Pad_DeviceConfigurationItem_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect to the runtime before trying to read the configuration.
        /// </summary>
        public static string Solution_Pad_DeviceConfigurationItem_NotConnected_Message {
            get {
                return ResourceManager.GetString("Solution_Pad_DeviceConfigurationItem_NotConnected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        public static string Solution_Pad_DeviceConfigurationItem_NotConnected_Title {
            get {
                return ResourceManager.GetString("Solution_Pad_DeviceConfigurationItem_NotConnected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Device Configuration.
        /// </summary>
        public static string Solution_Pad_DeviceConfigurationItem_ReadDeviceConfiguration {
            get {
                return ResourceManager.GetString("Solution_Pad_DeviceConfigurationItem_ReadDeviceConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the I/O configuration from the runtime.
        /// </summary>
        public static string Solution_Pad_DeviceConfigurationItem_ReadDeviceConfiguration_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_DeviceConfigurationItem_ReadDeviceConfiguration_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Off.
        /// </summary>
        public static string Solution_Pad_DiscreteInputItem_ForceOff {
            get {
                return ResourceManager.GetString("Solution_Pad_DiscreteInputItem_ForceOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the input to the off state, regardless of the actual hardware input.
        /// </summary>
        public static string Solution_Pad_DiscreteInputItem_ForceOff_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_DiscreteInputItem_ForceOff_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force On.
        /// </summary>
        public static string Solution_Pad_DiscreteInputItem_ForceOn {
            get {
                return ResourceManager.GetString("Solution_Pad_DiscreteInputItem_ForceOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the input to the on state, regardless of the actual hardware input.
        /// </summary>
        public static string Solution_Pad_DiscreteInputItem_ForceOn_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_DiscreteInputItem_ForceOn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Force.
        /// </summary>
        public static string Solution_Pad_DiscreteInputItem_RemoveForce {
            get {
                return ResourceManager.GetString("Solution_Pad_DiscreteInputItem_RemoveForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes any active force on the input, so it will return to the state of the hardware input.
        /// </summary>
        public static string Solution_Pad_DiscreteInputItem_RemoveForce_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_DiscreteInputItem_RemoveForce_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Off.
        /// </summary>
        public static string Solution_Pad_DiscreteOutputItem_ForceOff {
            get {
                return ResourceManager.GetString("Solution_Pad_DiscreteOutputItem_ForceOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the output to the off state, regardless of the logic driving it.
        /// </summary>
        public static string Solution_Pad_DiscreteOutputItem_ForceOff_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_DiscreteOutputItem_ForceOff_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force On.
        /// </summary>
        public static string Solution_Pad_DiscreteOutputItem_ForceOn {
            get {
                return ResourceManager.GetString("Solution_Pad_DiscreteOutputItem_ForceOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the output to the on state, regardless of the logic driving it.
        /// </summary>
        public static string Solution_Pad_DiscreteOutputItem_ForceOn_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_DiscreteOutputItem_ForceOn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Force.
        /// </summary>
        public static string Solution_Pad_DiscreteOutputItem_RemoveForce {
            get {
                return ResourceManager.GetString("Solution_Pad_DiscreteOutputItem_RemoveForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes any active force on the output, so it will return control to the application logic.
        /// </summary>
        public static string Solution_Pad_DiscreteOutputItem_RemoveForce_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_DiscreteOutputItem_RemoveForce_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_Add {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Page.
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_Add_Page {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_Add_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A page is where you write the logic for your application..
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_Add_Page_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_Add_Page_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Folder.
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_Add_PageCollection {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_Add_PageCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A subfolder that can hold pages.  A great way to organize your logic..
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_Add_PageCollection_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_Add_PageCollection_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_Delete {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this folder from the tree..
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_Delete_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_Delete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is not empty.  Deleting pages and folders can&apos;t be undone.  Are you sure you want to delete it?.
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_DeleteTitle {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logic.
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_LogicRootName {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_LogicRootName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_MoveDown {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the selected folder after the next folder (if possible).
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_MoveDown_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_MoveDown_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_MoveUp {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move the selected folder before the previous folder (if possible).
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_MoveUp_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_MoveUp_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string Solution_Pad_PageCollectionItem_NewPageCollectionName {
            get {
                return ResourceManager.GetString("Solution_Pad_PageCollectionItem_NewPageCollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string Solution_Pad_PageItem_Delete {
            get {
                return ResourceManager.GetString("Solution_Pad_PageItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes this page from the tree..
        /// </summary>
        public static string Solution_Pad_PageItem_Delete_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_PageItem_Delete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page contains logic.  Deleting a page can&apos;t be undone.  Are you sure you want to delete it?.
        /// </summary>
        public static string Solution_Pad_PageItem_DeleteConfirmation {
            get {
                return ResourceManager.GetString("Solution_Pad_PageItem_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete page.
        /// </summary>
        public static string Solution_Pad_PageItem_DeleteTitle {
            get {
                return ResourceManager.GetString("Solution_Pad_PageItem_DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string Solution_Pad_PageItem_MoveDown {
            get {
                return ResourceManager.GetString("Solution_Pad_PageItem_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the selected page down after the next page (if possible).
        /// </summary>
        public static string Solution_Pad_PageItem_MoveDown_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_PageItem_MoveDown_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string Solution_Pad_PageItem_MoveUp {
            get {
                return ResourceManager.GetString("Solution_Pad_PageItem_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves the selected page up before the previous page (if possible).
        /// </summary>
        public static string Solution_Pad_PageItem_MoveUp_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_PageItem_MoveUp_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Page.
        /// </summary>
        public static string Solution_Pad_PageItem_NewPageName {
            get {
                return ResourceManager.GetString("Solution_Pad_PageItem_NewPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string Solution_Pad_RootSolutionItem_Add {
            get {
                return ResourceManager.GetString("Solution_Pad_RootSolutionItem_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Runtime Application.
        /// </summary>
        public static string Solution_Pad_RootSolutionItem_Add_RuntimeApplication {
            get {
                return ResourceManager.GetString("Solution_Pad_RootSolutionItem_Add_RuntimeApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A container for the program that will control the system.\nThis will be downloaded as a unit to the controller (on this PC or elsewhere)..
        /// </summary>
        public static string Solution_Pad_RootSolutionItem_Add_RuntimeApplication_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_RootSolutionItem_Add_RuntimeApplication_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Properties....
        /// </summary>
        public static string Solution_Pad_RootSolutionItem_Properties {
            get {
                return ResourceManager.GetString("Solution_Pad_RootSolutionItem_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the solution properties window..
        /// </summary>
        public static string Solution_Pad_RootSolutionItem_Properties_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_RootSolutionItem_Properties_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_Connect {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a connection to the runtime.
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_Connect_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_Connect_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected successfully.  Application versions match..
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_ConnectedMessage {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_ConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_ConnectedTitle {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_ConnectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_Delete {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes this runtime application from the solution..
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_Delete_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_Delete_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_Disconnect {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the connection to the runtime.
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_Disconnect_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_Disconnect_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download?.
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_DownloadTitle {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_DownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no application in the runtime.  Do you want to download?.
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_NoApplication {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_NoApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to runtime..
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_NotConnectedMessage {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_NotConnectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_NotConnectedTitle {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_NotConnectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Properties....
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_Properties {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the runtime application properties window..
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_Properties_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_Properties_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must save before connecting.  Do you want to Save?.
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_Save {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_SaveTitle {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_SaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_Start {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the runtime engine executing (must be connected first).
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_Start_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_Start_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_Stop {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the execution of the runtime engine (must be connected first).
        /// </summary>
        public static string Solution_Pad_RuntimeApplicationItem_Stop_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_RuntimeApplicationItem_Stop_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force.
        /// </summary>
        public static string Solution_Pad_StringInputItem_Force {
            get {
                return ResourceManager.GetString("Solution_Pad_StringInputItem_Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the input to a specific value, regardless of the actual hardware input.
        /// </summary>
        public static string Solution_Pad_StringInputItem_Force_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_StringInputItem_Force_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Force.
        /// </summary>
        public static string Solution_Pad_StringInputItem_RemoveForce {
            get {
                return ResourceManager.GetString("Solution_Pad_StringInputItem_RemoveForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes any active force on the output, so it will return control to the application logic.
        /// </summary>
        public static string Solution_Pad_StringInputItem_RemoveForce_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_StringInputItem_RemoveForce_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force.
        /// </summary>
        public static string Solution_Pad_StringOutputItem_Force {
            get {
                return ResourceManager.GetString("Solution_Pad_StringOutputItem_Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the output to a specific value, regardless of the logic driving it.
        /// </summary>
        public static string Solution_Pad_StringOutputItem_Force_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_StringOutputItem_Force_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Force.
        /// </summary>
        public static string Solution_Pad_StringOutputItem_RemoveForce {
            get {
                return ResourceManager.GetString("Solution_Pad_StringOutputItem_RemoveForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes any active force on the output, so it will return control to the application logic.
        /// </summary>
        public static string Solution_Pad_StringOutputItem_RemoveForce_ToolTip {
            get {
                return ResourceManager.GetString("Solution_Pad_StringOutputItem_RemoveForce_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Explorer.
        /// </summary>
        public static string Solution_Pad_Title {
            get {
                return ResourceManager.GetString("Solution_Pad_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none loaded.
        /// </summary>
        public static string Solution_Root_NotLoadedHeader {
            get {
                return ResourceManager.GetString("Solution_Root_NotLoadedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Solution As....
        /// </summary>
        public static string Solution_SaveAsFileDialog_Title {
            get {
                return ResourceManager.GetString("Solution_SaveAsFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        public static string Solution_ToolBar_Name {
            get {
                return ResourceManager.GetString("Solution_ToolBar_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UploadDownloadDialog_Buttons_Cancel {
            get {
                return ResourceManager.GetString("UploadDownloadDialog_Buttons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Ok   .
        /// </summary>
        public static string UploadDownloadDialog_Buttons_Ok {
            get {
                return ResourceManager.GetString("UploadDownloadDialog_Buttons_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the application from the editor to the runtime engine.
        /// </summary>
        public static string UploadDownloadDialog_Download {
            get {
                return ResourceManager.GetString("UploadDownloadDialog_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to:.
        /// </summary>
        public static string UploadDownloadDialog_Header {
            get {
                return ResourceManager.GetString("UploadDownloadDialog_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application in the editor is completely different from the one in the runtime engine..
        /// </summary>
        public static string UploadDownloadDialog_Message_ApplicationMismatch {
            get {
                return ResourceManager.GetString("UploadDownloadDialog_Message_ApplicationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application versions in the runtime and the editor don&apos;t match (but they are different versions of the same application)..
        /// </summary>
        public static string UploadDownloadDialog_Message_VersionMismatch {
            get {
                return ResourceManager.GetString("UploadDownloadDialog_Message_VersionMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload/Download Runtime Application.
        /// </summary>
        public static string UploadDownloadDialog_Title {
            get {
                return ResourceManager.GetString("UploadDownloadDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload the application from the engine into the editor.
        /// </summary>
        public static string UploadDownloadDialog_Upload {
            get {
                return ResourceManager.GetString("UploadDownloadDialog_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        public static string Validation_Error {
            get {
                return ResourceManager.GetString("Validation_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2010 SoapBox Automation Inc..
        /// </summary>
        public static string Workbench_AboutBox_Copyright {
            get {
                return ResourceManager.GetString("Workbench_AboutBox_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released under the GPLv3 License..
        /// </summary>
        public static string Workbench_AboutBox_License {
            get {
                return ResourceManager.GetString("Workbench_AboutBox_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    Ok   .
        /// </summary>
        public static string Workbench_AboutBox_Ok {
            get {
                return ResourceManager.GetString("Workbench_AboutBox_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Snap is Not A PLC&quot;.
        /// </summary>
        public static string Workbench_AboutBox_Slogan {
            get {
                return ResourceManager.GetString("Workbench_AboutBox_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About SoapBox Snap.
        /// </summary>
        public static string Workbench_AboutBox_Title {
            get {
                return ResourceManager.GetString("Workbench_AboutBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoapBox Snap, &quot;Snap is not a PLC&quot; and the wolf cub image are trademarks of SoapBox Automation Inc..
        /// </summary>
        public static string Workbench_AboutBox_Trademark {
            get {
                return ResourceManager.GetString("Workbench_AboutBox_Trademark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display information about SoapBox Snap.
        /// </summary>
        public static string Workbench_Command_Tooltip_About {
            get {
                return ResourceManager.GetString("Workbench_Command_Tooltip_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ».
        /// </summary>
        public static string Workbench_Documents_Editor_GroupHeaderText {
            get {
                return ResourceManager.GetString("Workbench_Documents_Editor_GroupHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install the language plugin for the following language: .
        /// </summary>
        public static string Workbench_Documents_Editor_LanguagePluginNotFound {
            get {
                return ResourceManager.GetString("Workbench_Documents_Editor_LanguagePluginNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Editor.
        /// </summary>
        public static string Workbench_Documents_Editor_Title {
            get {
                return ResourceManager.GetString("Workbench_Documents_Editor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string Workbench_Documents_StartPage_GettingStarted {
            get {
                return ResourceManager.GetString("Workbench_Documents_StartPage_GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Example Application.
        /// </summary>
        public static string Workbench_Documents_StartPage_LoadExample {
            get {
                return ResourceManager.GetString("Workbench_Documents_StartPage_LoadExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Program.
        /// </summary>
        public static string Workbench_Documents_StartPage_LoadNewSolution {
            get {
                return ResourceManager.GetString("Workbench_Documents_StartPage_LoadNewSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoapBox Snap News.
        /// </summary>
        public static string Workbench_Documents_StartPage_News {
            get {
                return ResourceManager.GetString("Workbench_Documents_StartPage_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoapBox Snap Start Page.
        /// </summary>
        public static string Workbench_Documents_StartPage_Title {
            get {
                return ResourceManager.GetString("Workbench_Documents_StartPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View SoapBox Snap Tutorial.
        /// </summary>
        public static string Workbench_Documents_StartPage_ViewTutorial {
            get {
                return ResourceManager.GetString("Workbench_Documents_StartPage_ViewTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string Workbench_MainMenu_File_Close {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New....
        /// </summary>
        public static string Workbench_MainMenu_File_New {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string Workbench_MainMenu_File_Open {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string Workbench_MainMenu_File_Save {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string Workbench_MainMenu_File_SaveAs {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string Workbench_MainMenu_Help_About {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Workbench_MainMenu_View_Instructions {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_View_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Instructions tool box, so you can drag new instructions into the editor..
        /// </summary>
        public static string Workbench_MainMenu_View_Instructions_ToolTip {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_View_Instructions_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution E_xplorer.
        /// </summary>
        public static string Workbench_MainMenu_View_SolutionExplorer {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_View_SolutionExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the solution explorer window to view the automation applications in your solution file..
        /// </summary>
        public static string Workbench_MainMenu_View_SolutionExplorer_ToolTip {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_View_SolutionExplorer_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoapBox Snap Start Page.
        /// </summary>
        public static string Workbench_MainMenu_View_StartPage {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_View_StartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the &quot;Start Page&quot; that normally launches automatically when SoapBox Snap starts..
        /// </summary>
        public static string Workbench_MainMenu_View_StartPage_ToolTip {
            get {
                return ResourceManager.GetString("Workbench_MainMenu_View_StartPage_ToolTip", resourceCulture);
            }
        }
    }
}
