//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapBox.Snap.Phidgets.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoapBox.Snap.Phidgets.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalogInput.
        /// </summary>
        public static string AnalogInput {
            get {
                return ResourceManager.GetString("AnalogInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnalogOutput.
        /// </summary>
        public static string AnalogOutput {
            get {
                return ResourceManager.GetString("AnalogOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phidgets.
        /// </summary>
        public static string DriverName {
            get {
                return ResourceManager.GetString("DriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phidget Advanced Servo.
        /// </summary>
        public static string Phidget_AdvancedServo_Name {
            get {
                return ResourceManager.GetString("Phidget_AdvancedServo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phidget Interface Kit 0-16-16.
        /// </summary>
        public static string Phidget_InterfaceKit_0_16_16_Name {
            get {
                return ResourceManager.GetString("Phidget_InterfaceKit_0_16_16_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phidget Interface Kit 0-0-4.
        /// </summary>
        public static string Phidget_InterfaceKit_004_Name {
            get {
                return ResourceManager.GetString("Phidget_InterfaceKit_004_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phidget Interface Kit 0-0-8.
        /// </summary>
        public static string Phidget_InterfaceKit_008_Name {
            get {
                return ResourceManager.GetString("Phidget_InterfaceKit_008_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phidget Interface Kit 0-8-8.
        /// </summary>
        public static string Phidget_InterfaceKit_088_Name {
            get {
                return ResourceManager.GetString("Phidget_InterfaceKit_088_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phidget Interface Kit 4-8-8.
        /// </summary>
        public static string Phidget_InterfaceKit_488_Name {
            get {
                return ResourceManager.GetString("Phidget_InterfaceKit_488_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phidget Interface Kit 8-8-8.
        /// </summary>
        public static string Phidget_InterfaceKit_888_Name {
            get {
                return ResourceManager.GetString("Phidget_InterfaceKit_888_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phidget Servo 1 Motor.
        /// </summary>
        public static string Phidget_ServoMotor_1_Name {
            get {
                return ResourceManager.GetString("Phidget_ServoMotor_1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phidget Servo 4 Motor.
        /// </summary>
        public static string Phidget_ServoMotor_4_Name {
            get {
                return ResourceManager.GetString("Phidget_ServoMotor_4_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phidget Servo 8 Motor.
        /// </summary>
        public static string Phidget_ServoMotor_8_Name {
            get {
                return ResourceManager.GetString("Phidget_ServoMotor_8_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phidget Text LCD 2 x 20.
        /// </summary>
        public static string Phidget_TextLCD_2x20_Name {
            get {
                return ResourceManager.GetString("Phidget_TextLCD_2x20_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servo.
        /// </summary>
        public static string ServoOutputName {
            get {
                return ResourceManager.GetString("ServoOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StringInput.
        /// </summary>
        public static string StringInput {
            get {
                return ResourceManager.GetString("StringInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StringOutput.
        /// </summary>
        public static string StringOutput {
            get {
                return ResourceManager.GetString("StringOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Phidget.
        /// </summary>
        public static string Unknown_Phidget_Name {
            get {
                return ResourceManager.GetString("Unknown_Phidget_Name", resourceCulture);
            }
        }
    }
}
