//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapBox.Snap.Runtime.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoapBox.Snap.Runtime.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Options_RuntimeOptions_General {
            get {
                return ResourceManager.GetString("Options_RuntimeOptions_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as a Service.
        /// </summary>
        public static string Options_RuntimeOptions_General_RunAsService {
            get {
                return ResourceManager.GetString("Options_RuntimeOptions_General_RunAsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: You will need administrator rights to install the service.  Changing these options will temporarily stop the runtime engine, and may require the editor to shut down.  You may have to restart the application..
        /// </summary>
        public static string Options_RuntimeOptions_General_RunAsServiceWarning {
            get {
                return ResourceManager.GetString("Options_RuntimeOptions_General_RunAsServiceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoapBox Snap Soft Runtime.
        /// </summary>
        public static string Options_RuntimeOptions_Header {
            get {
                return ResourceManager.GetString("Options_RuntimeOptions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoapBox Snap Soft Runtime.
        /// </summary>
        public static string Runtime_Name {
            get {
                return ResourceManager.GetString("Runtime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SoapBox Snap Runtime Service will now be installed and started.  You may be asked for administrator privileges to perform this operation..
        /// </summary>
        public static string RuntimeController_InstallMessage {
            get {
                return ResourceManager.GetString("RuntimeController_InstallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing service.
        /// </summary>
        public static string RuntimeController_InstallTitle {
            get {
                return ResourceManager.GetString("RuntimeController_InstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoapBox Snap must shut down to release all resources to the service.  Please restart it manually..
        /// </summary>
        public static string RuntimeController_ShutdownMessage {
            get {
                return ResourceManager.GetString("RuntimeController_ShutdownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down.
        /// </summary>
        public static string RuntimeController_ShutdownTitle {
            get {
                return ResourceManager.GetString("RuntimeController_ShutdownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SoapBox Snap Runtime Service will now be stopped and uninstalled.  You may be asked for administrator privileges to perform this operation..
        /// </summary>
        public static string RuntimeController_UninstallMessage {
            get {
                return ResourceManager.GetString("RuntimeController_UninstallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling service.
        /// </summary>
        public static string RuntimeController_UninstallTitle {
            get {
                return ResourceManager.GetString("RuntimeController_UninstallTitle", resourceCulture);
            }
        }
    }
}
