//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapBox.Snap.Twitter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoapBox.Snap.Twitter.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AuthenticateDialog_Buttons_Cancel {
            get {
                return ResourceManager.GetString("AuthenticateDialog_Buttons_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Ok  .
        /// </summary>
        public static string AuthenticateDialog_Buttons_Ok {
            get {
                return ResourceManager.GetString("AuthenticateDialog_Buttons_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Twitter Username and Password.
        /// </summary>
        public static string AuthenticateDialog_Title {
            get {
                return ResourceManager.GetString("AuthenticateDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Authenticate.
        /// </summary>
        public static string ContextMenu_Authenticate {
            get {
                return ResourceManager.GetString("ContextMenu_Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when authorizing your Twitter credentials..
        /// </summary>
        public static string ContextMenu_Authenticate_Fail {
            get {
                return ResourceManager.GetString("ContextMenu_Authenticate_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string ContextMenu_Authenticate_Fail_Title {
            get {
                return ResourceManager.GetString("ContextMenu_Authenticate_Fail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Twitter credentials were successfully authorized..
        /// </summary>
        public static string ContextMenu_Authenticate_Success {
            get {
                return ResourceManager.GetString("ContextMenu_Authenticate_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string ContextMenu_Authenticate_Success_Title {
            get {
                return ResourceManager.GetString("ContextMenu_Authenticate_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must authenticate the Twitter Driver using your own Twitter account credentials.
        /// </summary>
        public static string ContextMenu_Authenticate_ToolTip {
            get {
                return ResourceManager.GetString("ContextMenu_Authenticate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear Credentials.
        /// </summary>
        public static string ContextMenu_ClearCredentials {
            get {
                return ResourceManager.GetString("ContextMenu_ClearCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the Twitter Access Token from SoapBox Snap for this &quot;device&quot;..
        /// </summary>
        public static string ContextMenu_ClearCredentials_ToolTip {
            get {
                return ResourceManager.GetString("ContextMenu_ClearCredentials_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add.
        /// </summary>
        public static string Driver_ContextMenu_Add {
            get {
                return ResourceManager.GetString("Driver_ContextMenu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter User Status Monitor.
        /// </summary>
        public static string Driver_ContextMenu_Add_UserStatusMonitor {
            get {
                return ResourceManager.GetString("Driver_ContextMenu_Add_UserStatusMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a driver that lets you monitor your most recent tweet..
        /// </summary>
        public static string Driver_ContextMenu_Add_UserStatusMonitor_ToolTip {
            get {
                return ResourceManager.GetString("Driver_ContextMenu_Add_UserStatusMonitor_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string DriverName {
            get {
                return ResourceManager.GetString("DriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter User Status Monitor.
        /// </summary>
        public static string Twitter_UserStatusMonitor {
            get {
                return ResourceManager.GetString("Twitter_UserStatusMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Changed.
        /// </summary>
        public static string UserStatusMonitor_DiscreteInput0 {
            get {
                return ResourceManager.GetString("UserStatusMonitor_DiscreteInput0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Status.
        /// </summary>
        public static string UserStatusMonitor_StringInput0 {
            get {
                return ResourceManager.GetString("UserStatusMonitor_StringInput0", resourceCulture);
            }
        }
    }
}
